name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: 7ad1ae74-bd82-4e4e-b0a9-d5dc78b9683a
          GH_TOKEN: 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
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
